# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ckiptagger.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63kiptagger.proto\x12\x0e\x63kiptagger.api\x1a\x1egoogle/protobuf/wrappers.proto\"\xf8\x04\n\x1aGetWordSegmentationRequest\x12\x11\n\tsentences\x18\x01 \x03(\t\x12-\n\tenablePOS\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12-\n\tenableNER\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12/\n\tdelimiter\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12L\n\trecommend\x18\x05 \x03(\x0b\x32\x39.ckiptagger.api.GetWordSegmentationRequest.RecommendEntry\x12\x46\n\x06\x63oerce\x18\x06 \x03(\x0b\x32\x36.ckiptagger.api.GetWordSegmentationRequest.CoerceEntry\x1a\x30\n\x0eRecommendEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a-\n\x0b\x43oerceEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\xc0\x01\n\x06Result\x12M\n\tsentences\x18\x01 \x03(\x0b\x32:.ckiptagger.api.GetWordSegmentationRequest.Result.Sentence\x12L\n\x08\x65ntities\x18\x02 \x03(\x0b\x32:.ckiptagger.api.GetWordSegmentationRequest.Result.Sentence\x1a\x19\n\x08Sentence\x12\r\n\x05words\x18\x01 \x03(\t2~\n\x06Tagger\x12t\n\x13GetWordSegmentation\x12*.ckiptagger.api.GetWordSegmentationRequest\x1a\x31.ckiptagger.api.GetWordSegmentationRequest.Resultb\x06proto3')



_GETWORDSEGMENTATIONREQUEST = DESCRIPTOR.message_types_by_name['GetWordSegmentationRequest']
_GETWORDSEGMENTATIONREQUEST_RECOMMENDENTRY = _GETWORDSEGMENTATIONREQUEST.nested_types_by_name['RecommendEntry']
_GETWORDSEGMENTATIONREQUEST_COERCEENTRY = _GETWORDSEGMENTATIONREQUEST.nested_types_by_name['CoerceEntry']
_GETWORDSEGMENTATIONREQUEST_RESULT = _GETWORDSEGMENTATIONREQUEST.nested_types_by_name['Result']
_GETWORDSEGMENTATIONREQUEST_RESULT_SENTENCE = _GETWORDSEGMENTATIONREQUEST_RESULT.nested_types_by_name['Sentence']
GetWordSegmentationRequest = _reflection.GeneratedProtocolMessageType('GetWordSegmentationRequest', (_message.Message,), {

  'RecommendEntry' : _reflection.GeneratedProtocolMessageType('RecommendEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETWORDSEGMENTATIONREQUEST_RECOMMENDENTRY,
    '__module__' : 'ckiptagger_pb2'
    # @@protoc_insertion_point(class_scope:ckiptagger.api.GetWordSegmentationRequest.RecommendEntry)
    })
  ,

  'CoerceEntry' : _reflection.GeneratedProtocolMessageType('CoerceEntry', (_message.Message,), {
    'DESCRIPTOR' : _GETWORDSEGMENTATIONREQUEST_COERCEENTRY,
    '__module__' : 'ckiptagger_pb2'
    # @@protoc_insertion_point(class_scope:ckiptagger.api.GetWordSegmentationRequest.CoerceEntry)
    })
  ,

  'Result' : _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {

    'Sentence' : _reflection.GeneratedProtocolMessageType('Sentence', (_message.Message,), {
      'DESCRIPTOR' : _GETWORDSEGMENTATIONREQUEST_RESULT_SENTENCE,
      '__module__' : 'ckiptagger_pb2'
      # @@protoc_insertion_point(class_scope:ckiptagger.api.GetWordSegmentationRequest.Result.Sentence)
      })
    ,
    'DESCRIPTOR' : _GETWORDSEGMENTATIONREQUEST_RESULT,
    '__module__' : 'ckiptagger_pb2'
    # @@protoc_insertion_point(class_scope:ckiptagger.api.GetWordSegmentationRequest.Result)
    })
  ,
  'DESCRIPTOR' : _GETWORDSEGMENTATIONREQUEST,
  '__module__' : 'ckiptagger_pb2'
  # @@protoc_insertion_point(class_scope:ckiptagger.api.GetWordSegmentationRequest)
  })
_sym_db.RegisterMessage(GetWordSegmentationRequest)
_sym_db.RegisterMessage(GetWordSegmentationRequest.RecommendEntry)
_sym_db.RegisterMessage(GetWordSegmentationRequest.CoerceEntry)
_sym_db.RegisterMessage(GetWordSegmentationRequest.Result)
_sym_db.RegisterMessage(GetWordSegmentationRequest.Result.Sentence)

_TAGGER = DESCRIPTOR.services_by_name['Tagger']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETWORDSEGMENTATIONREQUEST_RECOMMENDENTRY._options = None
  _GETWORDSEGMENTATIONREQUEST_RECOMMENDENTRY._serialized_options = b'8\001'
  _GETWORDSEGMENTATIONREQUEST_COERCEENTRY._options = None
  _GETWORDSEGMENTATIONREQUEST_COERCEENTRY._serialized_options = b'8\001'
  _GETWORDSEGMENTATIONREQUEST._serialized_start=69
  _GETWORDSEGMENTATIONREQUEST._serialized_end=701
  _GETWORDSEGMENTATIONREQUEST_RECOMMENDENTRY._serialized_start=411
  _GETWORDSEGMENTATIONREQUEST_RECOMMENDENTRY._serialized_end=459
  _GETWORDSEGMENTATIONREQUEST_COERCEENTRY._serialized_start=461
  _GETWORDSEGMENTATIONREQUEST_COERCEENTRY._serialized_end=506
  _GETWORDSEGMENTATIONREQUEST_RESULT._serialized_start=509
  _GETWORDSEGMENTATIONREQUEST_RESULT._serialized_end=701
  _GETWORDSEGMENTATIONREQUEST_RESULT_SENTENCE._serialized_start=676
  _GETWORDSEGMENTATIONREQUEST_RESULT_SENTENCE._serialized_end=701
  _TAGGER._serialized_start=703
  _TAGGER._serialized_end=829
# @@protoc_insertion_point(module_scope)
